name: kafka-connect-storage-cloud
lang: unknown
lang_version: unknown
git:
  enable: true
github:
  enable: true
semaphore:
  enable: true
  pipeline_enable: false
  triggers:
  - tags
  - branches
  branches: []
